package com.itrustcambodia.push;

import com.itrustcambodia.pluggable.PluggableConstants;

public interface Constants extends PluggableConstants {

    int MAX = 10;

    String DATE_FORMAT = "dd-MMM-yyyy HH:ss:mm";

    String USER_AGENT = "user-agent";
    
//    String ROLE_REST = "ROLE_REST";
//
//    String ROLE_PAGE_CITY_MANAGEMENT = "ROLE_PAGE_CITY_MANAGEMENT";
//
//    String ROLE_PAGE_NEW_CITY = "ROLE_PAGE_NEW_CITY";
//
//    String ROLE_PAGE_EDIT_CITY = "ROLE_PAGE_EDIT_CITY";
//
//    String ROLE_PAGE_COUNTRY_MANAGEMENT = "ROLE_PAGE_COUNTRY_MANAGEMENT";
//
//    String ROLE_PAGE_NEW_COUNTRY = "ROLE_PAGE_NEW_COUNTRY";
//
//    String ROLE_PAGE_EDIT_COUNTRY = "ROLE_PAGE_EDIT_COUNTRY";
//
//    String ROLE_PAGE_MANUFACTURE_MANAGEMENT = "ROLE_PAGE_MANUFACTURE_MANAGEMENT";
//
//    String ROLE_PAGE_NEW_MANUFACTURE = "ROLE_PAGE_NEW_MANUFACTURE";
//
//    String ROLE_PAGE_EDIT_MANUFACTURE = "ROLE_PAGE_EDIT_MANUFACTURE";
//
//    String ROLE_PAGE_MODEL_MANAGEMENT = "ROLE_PAGE_MODEL_MANAGEMENT";
//
//    String ROLE_PAGE_NEW_MODEL = "ROLE_PAGE_NEW_MODEL";
//
//    String ROLE_PAGE_EDIT_MODEL = "ROLE_PAGE_EDIT_MODEL";
//
//    String ROLE_PAGE_PLATFORM_MANAGEMENT = "ROLE_PAGE_PLATFORM_MANAGEMENT";
//
//    String ROLE_PAGE_NEW_PLATFORM = "ROLE_PAGE_NEW_PLATFORM";
//
//    String ROLE_PAGE_EDIT_PLATFORM = "ROLE_PAGE_EDIT_PLATFORM";
//
//    String ROLE_PAGE_VERSION_MANAGEMENT = "ROLE_PAGE_VERSION_MANAGEMENT";
//
//    String ROLE_PAGE_NEW_VERSION = "ROLE_PAGE_NEW_VERSION";
//
//    String ROLE_PAGE_EDIT_VERSION = "ROLE_PAGE_EDIT_VERSION";
//
//    String ROLE_PAGE_APPLICATION_MANAGEMENT = "ROLE_PAGE_APPLICATION_MANAGEMENT";
//
//    String ROLE_PAGE_NEW_APPLICATION = "ROLE_PAGE_NEW_APPLICATION";
//
//    String ROLE_PAGE_EDIT_APPLICATION = "ROLE_PAGE_EDIT_APPLICATION";
//
//    String ROLE_PAGE_PUSH_MESSAGE = "ROLE_PAGE_PUSH_MESSAGE";
//
//    String ROLE_PAGE_SETTING = "ROLE_PAGE_SETTING";
//    
//    String ROLE_PAGE_USER_PROFILE = "ROLE_PAGE_USER_PROFILE";
//
//    String ROLE_PAGE_DASHBOARD = "ROLE_PAGE_DASHBOARD";
//    
//    String ROLE_PAGE_NEW_DEVICE = "ROLE_PAGE_NEW_DEVICE";

}
